[package]
name = "opinion-renamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
doe = { version = "1.1.37", features = ["docx"] }
regex = "1.10.6"
walkdir = "2.5.0"
